### ISSUE TITLE
issuingDateTime is not parsed correctly from UHEAD Record

### ISSUE THREAD

**Issue by andrewko** [UnionInternationalCheminsdeFer/UIC-barcode#24]
When parsing the DateTime, wrong format is used.

**Input:** issuingDateString = 260420211458 (= Edition time im Format "DDMMYYYYHHMM")

org.uic.barcode.staticFrame.UHEADDataRecord: Row 183

```
SimpleDateFormat formatter = new SimpleDateFormat("ddMMyyyyhhmm");
try {
   issuingDate = formatter.parse(issuingDateString);
} catch (ParseException e) {
  e.printStackTrace();
}
```

h - Hour in am/pm (1-12)
H - Hour in day (0-23)

Use `ddMMyyyyHHmm` instead of `ddMMyyyyhhmm`

**Comment by CGantert345** [comment]
solved in version 1.2.5
