### ISSUE TITLE
BigInteger methods not supported pre Java 8 (*Exact())

### ISSUE THREAD

**Issue by irrationalism** [UnionInternationalCheminsdeFer/UIC-barcode#3]
https://github.com/UnionInternationalCheminsdeFer/UIC-barcode/blob/425bd35c736b7e1c0dbe5b3f9162e195b3be6018/src/org/uic/barcode/asn1/uper/IntCoder.java#L226

- resultValue.longValueExact()
- resultValue.intValueExact()
- resultValue.shortValueExact()

Those methods are not available pre Java 8 which is not fully supported on Android. Therefore the library cannot be used without modifications on Android. See [BigInteger-Diff](http://hg.openjdk.java.net/jdk8/jdk8/jdk/rev/2a8072c7cf99) for further details.

**Comment by CGantert345** [comment]
replaced by older functions and content validation
