### ISSUE TITLE
Generating AztecCode for a Ticket issued at midnight fails with a Nullpointer Exception

### ISSUE THREAD

**Issue by andrewko** [UnionInternationalCheminsdeFer/UIC-barcode#33]
A Nullpointer Exception occurs in org.uic.barcode.asn1.uper.SequenceCoder.canEncode(SequenceCoder.java:16) when a ticket has been issued at midnight. The reason is line 329 in org.uic.barcode.ticket.api.asn.omv3.IssuingData:

		int time =  cal.get(Calendar.HOUR_OF_DAY) * 60 + cal.get(Calendar.MINUTE);
		if (time > 0) {
			this.issuingTime = new Long (time );
		}

When IssuingDetail.issuingDate="2021-10-06T00:00:03.557", then _time_ is 0, _this.issuingTime_ in not initialised and causes a NPE in SequenceCoder.

**Comment by CGantert345** [comment]
Thanks for you contribution.  The bug is fixed with version 1.2.7.
