### ISSUE TITLE
ASN file : module name

### ISSUE THREAD

**Issue by jano42** [UnionInternationalCheminsdeFer/UIC-barcode#43]
Hi

From the misc folder I can found 3 ASN files.
All files are linked together since they are describing the same set of definitions.

Each file [uicRailTicketData_v3.0.0.asn](https://github.com/UnionInternationalCheminsdeFer/UIC-barcode/blob/master/misc/uicRailTicketData_v3.0.0.asn), [uicDynamicContentData_v1.0.1.asn](https://github.com/UnionInternationalCheminsdeFer/UIC-barcode/blob/master/misc/uicDynamicContentData_v1.0.1.asn) and [uicBarcodeHeader_v2.0.0.asn](https://github.com/UnionInternationalCheminsdeFer/UIC-barcode/blob/master/misc/uicBarcodeHeader_v2.0.0.asn) starts by defining the same ASN module name.

```asn
ASN-Module DEFINITIONS AUTOMATIC TAGS ::= BEGIN
```

When I want to merge all three files together in tools, I get some problem, because using the same module name in multiple files is not legal.  The X.680 specification ([https://www.itu.int/rec/T-REC-X.680-202102-I/en](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.itu.int%2Frec%2FT-REC-X.680-202102-I%2Fen&data=04%7C01%7CJeanmichel.Decoret%40conduent.com%7C264994e2d8eb4dcaec6b08d9f2424794%7C1aed4588b8ce43a8a775989538fd30d8%7C0%7C0%7C637807188754532593%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rdYAEdFH%2FhI38QZsCoS7Fn8SVAgIWUkDAVoIHHH57fg%3D&reserved=0)) states this:

> 
> Section 13.6 in X.680:
> 
> 13.6 The "modulereference" appearing in the "ModuleIdentifier" production is called the module name.
> NOTE – The possibility of defining a single ASN.1 module by the use of several occurrences of "ModuleBody" assigned the same "modulereference" was (arguably) permitted in earlier specifications. It is not permitted by this Recommendation | International Standard.
> 
> Section 13.7 in X.680:
> 
> 13.7 Module names shall be used only once (except as specified in 13.10) within the sphere of interest of the definition of the module.
> 

I would suggest to simply change the module definition for each file, for example:
   *   uicDynamicContentData_v1.0.1.asn  `ASN-Module-DynamicContentData DEFINITIONS AUTOMATIC TAGS ::= BEGIN`
   *   uicRailTicketData_v3.0.0.asn `ASN-Module-RailTicketData DEFINITIONS AUTOMATIC TAGS ::= BEGIN`

Thanks

**Comment by CGantert345** [comment]
The module names have been changed.
