### ISSUE TITLE
Adapt Standard Directory Layout for Java projects and more

### ISSUE THREAD

**Issue by irrationalism** [UnionInternationalCheminsdeFer/UIC-barcode#5]
The project is not structured in a [standard way](http://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html). For example the unit tests are not recognized as those. The IDE or the build system expects them in another places and the repositioning is not configured correctly.

The project cannot be build as-it-is because the dependencies are not handled very well. No external dependencies are defined in the pom.xml. Some class path extensions are pointed to local files.
https://github.com/UnionInternationalCheminsdeFer/UIC-barcode/blob/cd56532486900428f1ce6a661d825e066576ef86/.classpath#L10

This can easily be replaced with [bcprov-jdk15to18](https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk15to18). Same for junit which is an unsatisfied dependency by now.

**Comment by CGantert345** [comment]
structure has been updated to support non-eclipse builds

**Comment by CGantert345** [comment]
structure anchanged and maven dependencies added
