### ISSUE TITLE
FEATURE REQUEST: Add support for SSB barcodes

### ISSUE THREAD

**Issue by craftbyte** [UnionInternationalCheminsdeFer/UIC-barcode#55]
Since this library already supports both TLB and FCB, I was wondering if it would be possible to also support the Small Structured Barcode. If there is interest, I may try to venture down that path myself or let UIC handle it. For reference, see [ERA TAP TSI B12](https://www.era.europa.eu/sites/default/files/library/docs/recommendation/era_rec122_tap_tsi_revision_recommendation_technical_document_b12_en.pdf) page 19-30.

**Comment by CGantert345** [comment]
It could be included, However it is unclear whether SSB will be in much use in future.

**Comment by CGantert345** [comment]
added in branch ssb-barcodes. Implementation of tests is still pending.

**Comment by craftbyte** [comment]
Great news! Let me know if you need any sample barcodes, as I may have some tickets lying around (At least Slovenian Railways still issues SSB)

**Comment by CGantert345** [comment]
released in version 1.4.0
