### ISSUE TITLE
Mappings for Deutschlandticket

### ISSUE THREAD

**Issue by irrationalism** [UnionInternationalCheminsdeFer/UIC-barcode#56]
I am not able to generate a fully compliant Deutschlandticket (specs are just drafts for now) from this library. 

Considering `org.uic.barcode.Encoder` as entry point and the high level constructor in it, we need `org.uic.barcode.ticket.api.spec.IUicRailTicket` as one of the parameters. In `IUicRailTicket` we can specify `org.uic.barcode.ticket.api.spec.IIssuingDetail` which does not provide fields like `issuerNum`, `issuingYear` etc. that are needed for Deutschlandticket. 

Only parts of `org.uic.barcode.ticket.api.asn.omv3.IssuingData` (and `UicRailTicketData`) are exposed to the high level interface.

Is there another way to fill those fields without writing a new `Encoder`, `UFLEXDataRecord`, `StaticFrame` etc.?

Spec (draft): 
<img src="https://user-images.githubusercontent.com/80882762/212865767-83380c8b-badd-4f04-87fa-3f15c0a66109.png" alt="drawing" width="200"/>

**Comment by CGantert345** [comment]
- setting the issuing date setIssuingDate(Date date) will also set the issuingYear. 

- setIssuer(...)  will set either issuerNum or IssuerIA5 depending on whether the value is numeric or not. Setting different values in the xxxNum and xxxIA5 fields is not permitted by the specification and would be an error. The Num/IA5 split is only for optimizing the data size, not for different content.
