### ISSUE TITLE
Inflating issue with Steiermark Tickets

### ISSUE THREAD

**Issue by andrewko** [UnionInternationalCheminsdeFer/UIC-barcode#58]
Hi,

we have a problem with validating a 'Steiermark Ticket'. The example ticket is in the following ZIP file: [Steiermark Ticket.zip](https://github.com/UnionInternationalCheminsdeFer/UIC-barcode/files/10911170/Steiermark.Ticket.zip)

The inflate loop in [StaticFrame.java](https://github.com/UnionInternationalCheminsdeFer/UIC-barcode/blob/master/src/main/java/org/uic/barcode/staticFrame/StaticFrame.java#L507) stucks in an endless loop.

inflater.finished() never returns true

According to an very old [bug ](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4795299) it is also recommended to check the return value of inflater.inflate(). Recommended solution would look like:

`		while (!inflater.finished()) {  `
`			int count = inflater.inflate(inflatedDataBuffer,0,2000);`
`			if (inflater.needsDictionary() || count == 0) {`
`				break;`
`			}  `

Thanks in advance,

Andrej

**Comment by dstrobelOEBB** [comment]
Hi Clemens,
just to make sure. This is an issue coming from ÖBB side :)
Thanks for looking into it.
Daniel

**Comment by CGantert345** [comment]
the recommended change is added to the master.

Would you need a release of the binary imediately? Otherwise i would wait for the SSB branch to be completed.

**Comment by CGantert345** [comment]
released in version 1.4.0
