### ISSUE TITLE
Issuer gets lost on encoding/decoding

### ISSUE THREAD

**Issue by irrationalism** [UnionInternationalCheminsdeFer/UIC-barcode#61]
We have the requirement of using of different entities as ticket issuer and security issuer. This is possible by using the following data structures:

```java
org.uic.barcode.ticket.api.spec.IIssuingDetail issuingDetail = ...

// Bereitsteller des Schlüssels
issuingDetail.setSecurityProvider("1111");
// Ticketherausgeber-RICS-Code
issuingDetail.setIssuer("2222");
// optional: Ausgebendes (E)VU/Transport
issuingDetail.setIssuerName("myCompany");

// data looks valid after calling those setters
```

After a simple encoding/decoding of the generated ticket by using `org.uic.barcode.Encoder` and `org.uic.barcode.Decoder` 
- `issuingDetail.issuer` is set to `null` which triggers the getter to return the `securityProvider` field (`1111`),
- `issuerName` is correctly set to `myCompany`.

We are using/have to use `barcodeType` = 1  and `fcbVersion` = 13.

Any thoughts?

**Comment by CGantert345** [comment]
fixed in release 1.4.1

Note: the securityProvider is replaced by the securityProvider provided in the function signLevel1(...).
