### ISSUE TITLE
Exception decoding Interrail Pass

### ISSUE THREAD

**Issue by NicolaDelCore2** [UnionInternationalCheminsdeFer/UIC-barcode#66]
We receive a indexOfBound trying to decode the attached barcode
java.lang.ArrayIndexOutOfBoundsException: length=668; index=668 at org.uic.barcode.staticFrame.UTLAYDataRecord.decodeString(UTLAYDataRecord.java:60) at org.uic.barcode.staticFrame.UTLAYDataRecord.decodeContent(UTLAYDataRecord.java:137)

Base64:
I1VUMDE5OTAxVFQwMDEwLAIUNSMMrRGIB8fL3UcWDUxGq2yI5YICFEtBKOXG+1iZAAHvKzvpQNsmkR4CAAAAADAzNzd4nFVSTWvDMAz9KzoHmkl2HKdHL3FpIHWK63T0VAYrbDB22MZ+/yT3MyYJSJbee3rKdFx71yEhGr1cIsH9OGWXK7sgpQlJoUL+VuQDwHRMgztwU91gbBPf6IZvuZ1fPrWfousHTnMKK0lVwW28kFxrmljC7qMoipw4J6lpx8128BsfkosH2LrdDimDNNJj23EKKTLzDYconH7fT9+fr19vPygqCbXU6rbfc1RzbLIAmQ6VgPEwMougw+Kp7xYhosqI+cIUD+dPaVRUcXktKMZ105CYQV1xzd4NfccZBlbCrLSmEqkULbCAe4D6Tq47lzyMK3juY1qjzuwCx+qpLAp+xEf2jvCcL7AmnEVXUUqf7YYxeLg4dLauNuaxo6ZZZG8RoZ0x2RmTnaHYGYoVFVhnkG0cu6lNsmjSxD3ayh7sGIYDZJfgpU9rlrj3EVzossjtGBPvgCpjL+bIChQ++nExkMythiqeeQS4rol/iOYiBJe3H/cfqY6d6Q==

Nicola Del Core

**Comment by CGantert345** [comment]
The barcode contains an error. The UTLAY should include 38 elements, but the data content does not contain all of them.

**Comment by NicolaDelCore2** [comment]
We will report to the issuer.
Thanks

**Comment by CGantert345** [comment]
Testbarcode was outdated
