### ISSUE TITLE
Error decoding U_TLAY

### ISSUE THREAD

**Issue by sebastianknopf** [UnionInternationalCheminsdeFer/UIC-barcode#69]
I tried to decode an UIC918.3 ticket containing an U_TLAY record. 

Hex dump is:
`2355543031333037363030303035302D021442B57D8230E0A3522785D9FCCEF0B7CC0D588BDC02150097A92C9A053055846A3E2DDADBF06F57B36BA5680000003031393878DA554E4D8BC23010FD2B392AACF29249A6F5586C570F1E44DA8327911A68512254F7FFEF4C851603C99B791F99692EFBAA28618140848C8B73BBEB6BF3751CE01D1CD93C78949531CDA53E14670939E6D3B676968C016C0E2B578B32FEBD5F6DF7B8A6DBAAEEDB7B7CCBFF4E64AFB23FC42EC5C1FC3E9E437F4DB02AE90AA20986A0A00D8E71783DD322A62568B468FEB30C98794A397CEAA09DC4D7F230B299C15A80C739B38785C96786C46369F49032543527E97972F8CD8F6EEFB269EEEA1F74114753`

The ticket contains a U_TLAY in RCT2 format with 13 fields. But when I decode the ticket and look for ticket layout fields, there're no fields returned:

![grafik](https://github.com/UnionInternationalCheminsdeFer/UIC-barcode/assets/43302817/22b3f849-2642-4779-8f5b-92b456e2560f)

No exception or other error message. If I use another app to decode the raw data of the U_TLAY record, everything seems to be okay.

Could you take a look in here?

**Comment by sebastianknopf** [comment]
Same problem with this hex dump here:

`2355543031353231373030303031302D021500A7958EBB21072C93018BEF922A53F597AAE3B5E90214625157E0A477C8955BFC2F288B450F5AB85015920000003032333678DA554F5D4BC33014FD2B795470E5DCDC246D1F675BF5414146ABEC6954565D5997413705FF9B6FFE316F52E8F042B83987F391349B876A598200CB56535ABEAFBF5F0AF56F9022D5D04C6083B252AAD9D48FCBB59858EB55516B32220265C2E490C9EFDADDB86FC77327B11A4481243CB5DEABD77E187AA1444C26D0A6AC1795DFEE3FFDB65BDC16A0E0C064916DEDEC7FEEC6D3D15F75FE1A1C25C10F139E06E7DCECD298EE3620B127F20127676690C872B1E7A2C984C92E0C27314972A4405AF8FEF76738F71FEAEB7850313309C5EAAD3F45984D70F271CCE690C455B312ECE66493DF007F3C8154C0`

A valid UIC ticket is recognized, it contains 14 layout fields, but none are returned.

**Comment by CGantert345** [comment]
The barcode contains an error. The element "Number of fields" in the TLAY header is defined in the specification as numeric but is provied as a string. However the library can be made more robust to handle that error.

**Comment by sebastianknopf** [comment]
Thank you very much for fixing this one!
