### ISSUE TITLE
Barcodes with invalid header length and zlib header

### ISSUE THREAD

**Issue by ehambuch** [UnionInternationalCheminsdeFer/UIC-barcode#73]
In the past month I encountered some UIC 918-3 tickets that obviously

- larger header length (signature more than 50 bytes) which I discovered due to missing "length" field
- after that an invalid deflate/zlib header of 0x78C2

Does anyone have an idea about that format? In the official specification I cannot find anything about. Examples (full ticket can be provided):
`2355543031303038303030303037302C0214216D737E2D31C385C3A4C3812D79C2B97E72C3B0C2B1C2A4C29BC396C3B3021446C3893733C3B720C3B4585FC39265C38CC3BCC2BF61C38F55C390C2AC44000000003032323078C29C...`

and
`235554303133303736414D303133302E021500C29CC3914AC2B41472C2AAC2A3C2B4C3A41945C2A6C289C381C29638C2A4C2AAC3BD021500C387C2A7C288C29FC3865F1AC2915D6CC2B801C2AEC2B4C3BBC2B9C2BD2839C28500003034333778C29C0...`

**Comment by CGantert345** [comment]
Version 2 of the static barcode frame has extended elements for larger signatures (64 byte instead of 50).

**Comment by ehambuch** [comment]
Many thanks. I had two issues: the Aztec Code Reading SDK returned some corrupt data and the header is Version 1, although the ticket is obviously Version 2.
