### ISSUE TITLE
Dynamic Level Encoding Part missing in Code

### ISSUE THREAD

**Issue by apfelsine1** [UnionInternationalCheminsdeFer/UIC-barcode#76]
In the wiki it is said that for Dynamic Encoding  Level 1 & 2 to use something like

       Encoder encoder = new Encoder(ticket, layout, Encoder.UIC_BARCODE_TYPE_DYNAMIC, <frame version>, <FCB version>);

Encoder.UIC_BARCODE_TYPE_DYNAMIC does not exist.

How would the dynamic encoding for UIC 918-9 work here?

**Comment by CGantert345** [comment]
The wiki showed a wrong variable, it should be Encoder.UIC_BARCODE_TYPE_DYNAMIC.
