### ISSUE TITLE
issuingDate in UHEADDataRecord in 12h format insetead of 24h format

### ISSUE THREAD

**Issue by tobsesHub** [UnionInternationalCheminsdeFer/UIC-barcode#85]
## Problem
When creating a UIC ticket, I noticed that the issuingDate in the UHEADDataRecord seems to be coded incorrectly.
If I create a ticket with the issuingDate 21 o'clock and read in the created UIC code, I get the issuingDate 9' o'clock in the UHEADDataRecord 

## Possible solution

Use the 24 hours of the date and not in 12 hour format in the encodeContent method.

At least I think it should be in 24 hour format since the format “DDMMYYYYHHMM” in the UIC standard does not contain a value for PM/AM. To differentiate between 09:00AM and 09:00PM, you would have to take the hours in 24-hour format.

So instead of 
`		String timeElement = String.format("%02d%02d%04d%02d%02d", 
					                           now.get(Calendar.DAY_OF_MONTH),
					                           now.get(Calendar.MONTH) + 1,
					                           now.get(Calendar.YEAR),
					                           now.get(Calendar.HOUR),
					                           now.get(Calendar.MINUTE));
`

I would use the following code:
`		String timeElement = String.format("%02d%02d%04d%02d%02d", 
					                           now.get(Calendar.DAY_OF_MONTH),
					                           now.get(Calendar.MONTH) + 1,
					                           now.get(Calendar.YEAR),
					                           now.get(Calendar.HOUR_OF_DAY),
					                           now.get(Calendar.MINUTE));
`

https://docs.oracle.com/javase/8/docs/api/java/util/Calendar.html#HOUR_OF_DAY
https://docs.oracle.com/javase/8/docs/api/java/util/Calendar.html#HOUR

## PR
https://github.com/UnionInternationalCheminsdeFer/UIC-barcode/pull/86

**Comment by CGantert345** [comment]
meged.
thanks for the fix.
