### ISSUE TITLE
Incorrect parsing of SSB class data

### ISSUE THREAD

**Issue by craftbyte** [UnionInternationalCheminsdeFer/UIC-barcode#88]
The class data in SSB is parsed in the wrong way. Looking at TAP B.12, the translation is as follows (first class = 1, seconds class = 2, etc):

![image](https://github.com/user-attachments/assets/6780fa7d-b453-4a06-aa39-13c36a4d6c73)

This makes the decoder currently crash on second class tickets (like the one below):

![PXL_20241027_004846090](https://github.com/user-attachments/assets/7dac2cbc-5c34-4778-b71a-2a034d6c0de2)

How should we encode this into the enum? I think doing 1=first and 2=second makes sense, while we can leave the rest to be just their alphanum value?

https://github.com/UnionInternationalCheminsdeFer/UIC-barcode/blob/737120a46e7b1af55113d88daab7caf48173c232/src/main/java/org/uic/barcode/ssbFrame/SsbClass.java#L3-L8

**Comment by CGantert345** [comment]
fixed in 1.4.9
