### ISSUE TITLE
Signature verification is unreliable due to re-compression 

### ISSUE THREAD

**Issue by TheEnbyperor** [UnionInternationalCheminsdeFer/UIC-barcode#91]
When verifying the signature on `#UT` barcodes the ticket contents is re-encoded and re-compressed (see [here](https://github.com/UnionInternationalCheminsdeFer/UIC-barcode/blob/15c13a22610ad6e705b38e66ce3599b1ebe78df7/src/main/java/org/uic/barcode/staticFrame/StaticFrame.java#L297)) before verifying the signature over that. This could result in a different (but still valid) ZLib compression output that then fails signature verification.

Instead the compressed data as encoded in the Aztec should be used for signature verification.

**Comment by CGantert345** [comment]
The getDataForSignature() method is currently used for encoding and decoding. In decoding the signatureData are set in the "decode" method and are not reencoded. 

However to make this more transparent i would in the next version:

- Split getSignedData to buildSignedData (for encoding)
- and getSignedData to get the original signed data 
- and make both functions private.

**Comment by CGantert345** [comment]
changed with pull request#92
