### ISSUE TITLE
keyId in Dynamic Header does not allow for test key usage

### ISSUE THREAD

**Issue by craftbyte** [UnionInternationalCheminsdeFer/UIC-barcode#93]
Looking at the ASN.1 documentantion for the Dynamic Header, I noticed the following for Level1 data:

```
    	keyId		        INTEGER(0..99999)  OPTIONAL,
```

I was reading an old specification of [UIC 918.3](https://softbank.iust.ac.ir/Railway/Codes/UIC%20codes/UIC%201999-2007/anglais%202/e918x3.pdf). Since I do not possess the latest version of leaflet 90918-9 due to not being able to afford it, I cannot check the latest specification, but the old version specified keyId for test use have to start with `TT` (section 8.8.2). By using an integer now, and also not using something like a boolean to indicate using test keys, that part of the old specification did not get carried over. Could we add a BOOLEAN to indicate usage of test keys or change this to a 5 character string?

**Comment by CGantert345** [comment]
According to the IRS 90918.9 the "TT" indication for test keys does not apply to dynamic header barcodes. The boolean "specimen" in the barcode must be used to indicate a test ticket.
